on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Apache Tuweni version'     
        required: true
        default: '2.2.0'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
      - run: |
          make publish
