on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Apache Tuweni version'     
        required: true
        default: '2.2.0'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
      - run: |
          export VERSION=${{ github.event.inputs.version }}
          make publish
      - name: Run the Action
        uses: devops-infra/action-commit-push@v0.9.0
        with:
          github_token: "${{ secrets.TOKEN }}"
          add_timestamp: true
          commit_prefix: "[AUTO]"
          commit_message: "Commit changes ${{ github.event.inputs.version }}"
          force: false
          target_branch: main

