on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Apache Tuweni version'     
        required: true
        default: '2.2.0'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
    steps:
      - run: |
          echo $PGP_PRIVATE_KEY | gpg --import
          make publish
